---
title: "Technical Report"
author: "Kendra Swanson, Yifan Ma"
date: "4/28/2018"
output: html_document
---


### Abstract

  Using data on killings committed by police in the first half of 2015, we studied trends in demographic information about the victim and the location in which the killing took place. We grouped the data by the county in which the killing took place. We then normalized the number of deaths by dividing deaths by the sum of the population of the tracts in which the killings took place; we multipled this number by 1000, and the resulting values represent the sample killings by police per thousand people in that county. We studied the correlation of deaths per thousand with factors including poverty rate of the county, race of the victims, number of victims who were male, average college graduation rate, and average unemployment rate. We discovered that poverty statistics for the county, average unemployment rate and race of the victim does have a statistically significant impact on predicted deaths per thousand in that county at the hands of police.


### Introduction
  
  In 2014, the killings of Michael Brown and Eric Garner at the hands of police officers brought conversation about police violence into the national spotlight. Since then, there has been an increased interest in answering questions about the use of deadly force by police officers, as well as about racial bias in policing. Our question is, what demographic factors are correlated with who was killed by police in the first six months of 2015? We created a regression model which mapped deaths per thousand in a county to percentage of those victims who were men, percentage of those victims who were white, average poverty rate for the county, average unemployment rate, and average college graduation rate.
  We discovered that the strongest correlation existed between poverty rate and deaths per thousand. As poverty rate increases in a county, so do the deaths at the hands of police; the amount of variance explained by this value, however, is low. We also investigated patterns in race of the victims, and found certain statistically significant values that suggested the killings of non-white individuals in greater density than white individuals. Finally, we investigated a number of outlying counties with uncommonly high death rates, and found ____.
  Our analysis confirms some of the conversation around race and class bias in the police force. However, it should be noted that most of the variation in data is not explained by these factors. 
  

### The Data
  
  The data we used originates from a combination of census data and a set of data published in The Guardian called The Counted. The Counted is a crowdsourced record seeking to understand the full scope of police violence in the United States. Its cases are individuals who died at the hands of police officers, and it records the race, gender, and age of the individual, the location of the death, whether the victim was armed, and other case-specific information. Census data was used to determine the poverty rate in the area in which the death took place, as well as the unemployment rate, college graduation rate, and many other factors. The joining of this data was performed by fivethirtyeight.com.
  We further modified the data to group by county. The cases we used were counties in which police killings took place in the first six months of 2015. We used population data to estimate a sample value for deaths per thousand in each of these counties, and attempted to create a model predicting this value using the other census and case-specific variables.

### Results:

  In our multiple regression model, we examined five variables, percentage of those victims who were men, percentage of those victims who were white, average poverty rate for the county, average unemployment rate, and average college graduation rate. Among those demographic factors in the counties, we found that for every one percent increase in average poverty rate in the county, we would predict a 3 percent increase in death per thousand people in that county, holding all other variable constant. Similarly, we found that every one percent increase in unemployment rate in the county, we would predict a 41 percent increase in death per thousand people in that county, holding all other variable constant. Other explanatory variables in the multiple regression also slightly correlates with our response variable, death per thousand, however, we found no evidence that those correlation is significant. WHITE?
  We also checked the conditions for this regression model. Independence was assumed since each county and the people who was killed by police should be individual cases. Linearity of the model is acceptable since in the residuals vs. fitted model, the line is fairly horizontal and straight. Equal variance of the model could not be guaranteed since the plot does thicken. At last, from the QQ plot, normality of the residuals is also not satisfied, there are outliers that are obviously separated from the general trend.

### Conclusion:

  We examined demographic factors that contribute to death per thousand by police in each county during the first six months of 2015. Of all factors, average poverty rate and unemployment rate positively correlated with death per thousand. There is also a strong positive association between the average poverty rate and the unemployment rate, which explains why both factors contribute to our response variable in a similar manner. 
  The county data set that we used for the study has 300 observations with 12 variables, although it does not seem to be a small data set, a good portion of the  counties only had one or two deaths in the first six months of 2015. Due to the  smaller number of death recorded, we had to times death/population by 1000 so the statistics was not as small. The lower number of death in each individual county also created outliers. We observe outliers when examining correlations between…
One possible solution to the problems described above is to web scrap the police killing data and manually join other data from census to include more variables. Therefore, there will be more cases of death by policy killing per county and the analysis will be more meaningful.
  One other limitation of our data is that county’s identity could not be verify. One of the variables in the data frame contains county id, however, the id does not match any ids we examined through other online sources. As a result, when researching the outliers in the data set, only general statement about the city that the county resides could be analyzed. 


